urls:
  api: "https://devnet-api.multiversx.com"
  swagger:
    - "http://localhost:3000"
    - "https://sol-mvx-nft-bridge-poc-production.up.railway.app"
itheumSdk.environment: "devnet"
api:
  auth: true
features:
  publicApi:
    enabled: true
    port: 3000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - "http://localhost:3000"
    - "https://localhost:3000"
    - "https://utils.multiversx.com"
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
