[package]
name = "locknfts"
version = "0.0.1"
edition = "2021"
publish = false
authors = [ "Ovidiu Damian"]

[lib]
path = "src/lock.rs"

[dependencies.multiversx-sc]
version = "0.46.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.46.1"
